### ISSUE TITLE
mimics can't tp across dims

### ISSUE THREAD

**Issue by superon** [akoimeexx/mimics-mod#7]
yet the one i was just testing with at least loves diving through local nether portals.

**Comment by akoimeexx** [comment]
Odd, it should behave like any other Tameable. Do you have a video available to showcase this?

**Comment by akoimeexx** [comment]
> yet the one i was just testing with at least loves diving through local nether portals.

Odd, it should behave like any other Tameable. Do you have a video available to showcase this?

**Comment by superon** [comment]
no though it seems it's just because it randomly moves about, it randomly went through a portal.    should any other tameable tp across dims though? i don't think that's a thing.

**Comment by akoimeexx** [comment]
Sounds like any other tameable entity that wanders through a portal. I will tweak the weighted values for when it chooses to do something though to help balance out the amount of wandering they do. I almost think it'd be better to prevent wandering altogether if tamed (this would be opposite of how vanilla tamed mobs behave, eg wolves still wander unless sitting or leashed as well)

**Comment by akoimeexx** [comment]
Tested this, Mimics go through portals like any other entity. If you're doing this in a test world, remember to go through a nether portal you've newly created so there's actually a portal on the nether side as well.
