### ISSUE TITLE
unable to connect after finding mimic - server

### ISSUE THREAD

**Issue by superon** [akoimeexx/mimics-mod#9]
this maybe impossible to diagnose from what i have but it's the best i can do i think.
https://paste.ee/p/4Mp5j
possibly a compat issue idk

server console reported 
```
16.05 22:15:13 [Disconnect] User playername has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
16.05 22:15:13 [Server] Netty Epoll Server IO #2/ERROR java.lang.NullPointerException
```
 _(added codeblock to prevent issue linking -akoi)_
 
when attempting to connect.   i say "reported" bc i removed the mod so people can continue to play on the server

**Comment by akoimeexx** [comment]
Needs more info, the attached paste.ee doesn't seem to reference Mimics in the output as far as the exceptions being thrown there. I'll dig into the code a bit where client/server stuff happens to look for any glaring NPE possibilities in the meanwhile.

**Comment by akoimeexx** [comment]
Fixed; SP doesn't mind having a nullable tracked data, which is the "Food" nbt tag for the mimic. This defaults to nonexistent or empty when no food item has been set.

I've updated the code locally to set the Food tag to `""` on instance creation; this appears to have resolved it. Will commit the change shortly. Thanks for bringing this to my attention!

**Comment by akoimeexx** [comment]
Code pushed and updated version on CF & Modrinth
